#!/usr/bin/python
def decode(enc, i):
    o = list([0 for c in range(i)])
    s = 1
    c = 0
    for l in range(len(enc)):
        o[c] += 1
        c += s
        s = -s if(c == i - 1 or c == 0) else s

    ln = len(enc)
    enc = list(enc)
    out = []
    for n in range(i):
       out.append(list([enc.pop(0) for m in range(o[n])]))

    fin = []
    s = 1
    c = 0
    for l in range(ln):
        fin.append(out[c].pop(0))
        c += s
        s = -s if(c == i - 1 or c == 0) else s
    
    return "".join(fin)


def encode(dec, i):
    o = list([[] for c in range(i)])

    dec = list(dec)
    s = 1
    c = 0

    for n in dec:
        o[c].append(n)
        c += s
        s = -s if(c == i - 1 or c == 0) else s

    return "".join("".join(x) for x in o)


def main():
    dec = "WEATTACKATDAWNISACOMMONEXAMPLEPLAINTEXTSOIFIGUREWECANUSEITHERETOPROVETHATYOUHAVEDECRYPTEDTHISMESSAGESUCCESSFULLYSUBMITTHEWORDBIRDCAGEWHICHISAMOVIETHATISONTVWHILEIAMWRITINGTHISIAMADDINGALOTOFTEXTHERETOHELPTHOSEOFYOUTHATDECIDETODOCHARACTERFREQUNCYANALYSISWHICHISHONESTLYAPRETTYGOODSTRATEGYHOPEFULLYYOUALREADYHAVEBUILTORHAVEACCESSTOASOMETHINGTHATCANANALYSETEXTANDDETERMINEIFTHECHARACTERFREQUENCIESMATCHTHEENGLISHLANGUAGEBECAUSEITMAYTAKEAWHILETOROLLONEFROMSCRATCHWHILETRYINGTOSOLVETHISPROBLEM"
    enc = "WAPSDEXTCOEEREFSELIORSARCLIETEOIHHPVASTFEGBERIPAPNTOEGIAIATHDDHIYEACYERQAENOHRTETEVMEBGHMFEIOWSGFHCLXEUUCOMTOTLERESSDEWWORCCSHEUREATTEGALSEBAPXETIURWVRTEEHIOTLOSNACNNULCVLCMTHHHCOHTIOTDASNALTSANACASORLEKASTATCWINTLOTRYERYLTNDRILERAOMAXOITDEECOIAHAALSTYIOADAEHIOTSTEIEYESHHSNGEHCATSOUACEHSSTTCODNFSOTSTIIGNLTTNLDUBSTTCMIMEHTAOIUUPFTSTTIPUEAYOAEOAEEALALWGWMGNHYUIAAHDTORYAOLVMHRHTGYIHNNMUAARLMMHIDHYFCPGRAETMTCNTHIIIORCVCLBOTSAOFRNRYEHTGIFHEAWLYSCEEEEYUVEIMSOEUETAYHNNITEKAERAWDSIAEQTDIEHET"

    print("enc:", encode(dec, 17))
    print("dec:", decode(enc, 17))


if __name__ == "__main__":
    main()